import './style.css';
import { GlyphReachApp } from './app/App';
import { applyM9Chapter } from './app/m9-chapter';
import { applyStoryPolish } from './app/story-polish';
const root = document.querySelector<HTMLElement>('#app');
if (!root) throw new Error('GlyphReach root element not found');
const app = new GlyphReachApp();
void app.mount(root);
applyStoryPolish(root);
applyM9Chapter(root, app);
window.addEventListener('beforeunload', () => app.destroy(), { once: true });
